version: '3.8'

services:
  # Database MySQL
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"

  # Backend CodeIgniter
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_ci
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - app_network

  # Frontend Laravel
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_laravel
    restart: unless-stopped
    depends_on:
      - backend
      - mysql
    networks:
      - app_network

  # Web Server (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
