FROM php:8.1-fpm

# Install dependensi yang diperlukan
RUN apt-get update && apt-get install -y zip unzip curl git

# Clone kode dari GitHub
WORKDIR /var/www/html
ARG FRONTEND_REPO
RUN git clone ${FRONTEND_REPO} .
RUN chmod -R 777 /var/www/html

# Install Composer dan dependency Laravel
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install

EXPOSE 9000

CMD ["php-fpm"]
